---
title: "Time Series Classification with Keras in Python"
author: "Evan Woods"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.width = 6)
knitr::opts_chunk$set(fig.asp = 0.618)
knitr::opts_chunk$set(out.width = "70%")
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(
  comment = ""
)
```

<!-- ## Import Libraries -->
```{r}
if(!require("keras")) install.packages("keras") # Install keras for deep learning

library(keras)
reticulate::use_condaenv(condaenv = "r-tensorflow")
```

<!-- ## Functions -->
```{r}
# """
#   Purpose: This function will create a formatted output string that wraps at 80
#            characters. It is expected to be used in conjunction with sprintf().
#            It is intended for formatted printing while knitting.
#            I.E.: f_print(sprintf())
#            Note: This function does interpret newline characters. 
#   Parameters: 
#            string: sprintf() wrapped string to print. I.E.: sprintf('string')
#            
#   Returns: This function prints the input string.
# """
f_print <- function(string){
  cat(str_wrap(string = string, width = 80, indent = 0, exdent = 0, whitespace_only = TRUE))
}
```

```{python}
# """
#   Purpose: This function defines a model with 3 convolutional layers, 
#            a Global Average Pooling Layer, & an output layer.
#   Parameters: 
#            input_shape: The input shape of the data that is being processed.
#                         This data is a 1D time series.
#   Returns: Model: This is a keras model that may be trained. 
# """
def make_model(input_shape):
  input_layer = keras.layers.Input(input_shape)
  conv1 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(input_layer)
  conv1 = keras.layers.BatchNormalization()(conv1)
  conv1 = keras.layers.ReLU()(conv1)
  
  conv2 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(conv1)
  conv2 = keras.layers.BatchNormalization()(conv2)
  conv2 = keras.layers.ReLU()(conv2)
  
  conv3 = keras.layers.Conv1D(filters=64, kernel_size=3, padding="same")(conv2)
  conv3 = keras.layers.BatchNormalization()(conv3)
  conv3 = keras.layers.ReLU()(conv3)
  
  gap = keras.layers.GlobalAveragePooling1D()(conv3)
  
  output_layer = keras.layers.Dense(num_classes, activation="softmax")(gap)
  
  return keras.models.Model(inputs=input_layers, outputs=output_layer)
```



```{python}
import keras
import numpy as np
import matplotlib.pyplot as plt
```

```{python}
def readucr(filename):
  data = np.loadtxt(filename, delimiter="\t")
  y = data[:, 0]
  x = data[:, 1:]
  return x, y.astype(int)

root_url = "https://raw.githubusercontent.com/hfawaz/cd-diagram/master/FordA/"

x_train, y_train = readucr(root_url + "FordA_TRAIN.tsv")
x_test, y_test = readucr(root_url + "FordA_TEST.tsv")

classes = np.unique(np.concatenate((y_train, y_test), axis=0))

plt.figure()
for c in classes:
  c_x_train = x_train[y_train == c]
  plt.plot(c_x_train[0], label="class " + str(c))
plt.legend(loc="best")
plt.show()
plt.close()
```
```{python}
# Standardize the data
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))
```

```{python}
num_classes = len(np.unique(y_train))
```

```{python}
idx = np.random.permutation(len(x_train))
x_train = x_train[idx]
y_train = y_train[idx]
```

```{python}
y_train[y_train == -1] = 0
y_test[y_test] == -1] = 0
```

## Build the model
```{python}
model = make_model(input_shape=x_train.shape[1:])
keras.utils.plot_model(model, show_shapes=True)
```

## Training the model
```{python}
epochs = 500
batch_size = 32

callbacks = [
  keras.callbacks.ModelCheckpoint(
    "best_model.keras", save_best_only=True, monitor="val_loss"
  ), 
  keras.callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=20, min_lr=0.0001
  ),
  keras.callbacks.EarlyStopping(monitor="val_loss", patience=50, verbose=1)
]
model.compile(
  optimizer="adam", 
  loss = "sparse_categorical_crossentropy",
  metrics = ["sparse_categorical_accuracy"],
) 

history = model.fit(
  x_train,
  y_train,
  batch_size=batch_size,
  epochs=epochs, 
  callbacks=callbacks, 
  validation_split = 0.2, 
  verbose=1
)
```

# Evaluate Model on Test Data
```{python}
model = keras.models.load_model("best_model.keras")
test_loss, test_acc = model.evaluate(x_test, y_test)

print("Test accuracy", test_acc)
print("test loss", test_loss)
```

# Plot the model's training & validation loss
```{python}
metric = "sparse_categorical_accuracy"
plt.figure()
plt.plot(history.history[metric])
plt.plot(history.history["val_", + metric])
plt.title("model " + metric)
plt.ylabel(metric, fontsize="large")
plt.xlabel("epoch", fontsize="large")
plt.legend(["train", "val"], loc="best")
plt.show()
plt.close()
```

